services:
  entity-service-postgres:
    container_name: universe-simulator-entity-service-postgres
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_DB=entity-service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - entity-service-postgres:/var/lib/postgresql/data

volumes:
  entity-service-postgres:
