services:
  entity-service-postgres:
    container_name: universe-simulator-entity-service-postgres
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=entity-service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - entity-service-postgres:/var/lib/postgresql/data
  entity-service-redis:
    container_name: universe-simulator-entity-service-redis
    image: redis:7.0.2
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 120 1 --loglevel warning --requirepass uRnEiDvIeSrse
    volumes:
      - entity-service-redis:/var/lib/redis/data

volumes:
  entity-service-postgres:
  entity-service-redis:
