services:
  vault:
    image: vault
    container_name: universe-simulator-vault
    restart: always
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      - 'VAULT_LOCAL_CONFIG=
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:${US_VAULT_PORT}",
              "tls_disable": true
            }
          },
          "ui": true
        }'
    ports:
      - ${US_VAULT_PORT}:8200
    volumes:
      - vault-logs:/vault/logs
      - vault-file:/vault/file

  rabbitmq:
    image: rabbitmq:management
    container_name: universe-simulator-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${US_RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${US_RABBITMQ_DEFAULT_PASS}
    ports:
      - ${US_RABBITMQ_PORT}:5672
      - ${US_RABBITMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  entity-service-postgres:
    image: postgres
    container_name: universe-simulator-entity-service-postgres
    restart: always
    environment:
      - POSTGRES_DB=entity-service
      - POSTGRES_USER=${US_ES_POSTGRES_USER}
      - POSTGRES_PASSWORD=${US_ES_POSTGRES_PASSWORD}
    ports:
      - ${US_ES_POSTGRES_PORT}:5432
    volumes:
      - entity-service-postgres:/var/lib/postgresql/data

volumes:
  vault-logs:
  vault-file:
  rabbitmq:
  entity-service-postgres:
