version: '3.8'

services:
  postgres:
    image: postgres
    container_name: universe-simulator-entity-service-postgres
    restart: always
    environment:
      - POSTGRES_DB=${US_ES_POSTGRES_DB}
      - POSTGRES_USER=${US_ES_POSTGRES_USER}
      - POSTGRES_PASSWORD=${US_ES_POSTGRES_PASSWORD}
    ports:
      - ${US_ES_POSTGRES_PORT}:5432
    volumes:
      - entity-service-postgres:/var/lib/postgresql/data
  mysql:
    image: mysql
    container_name: entity-service-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - entity-service--mysql-volume:/var/lib/mysql/data

volumes:
  entity-service-postgres:
  entity-service--mysql-volume:
