version: '3.8'

services:
  postgres:
    image: postgres
    container_name: universe-simulator-entity-service-postgres
    restart: always
    environment:
      - POSTGRES_DB=${US_ES_POSTGRES_DB}
      - POSTGRES_USER=${US_ES_POSTGRES_USER}
      - POSTGRES_PASSWORD=${US_ES_POSTGRES_PASSWORD}
    ports:
      - ${US_ES_POSTGRES_PORT}:5432
    volumes:
      - entity-service-postgres:/var/lib/postgresql/data

  mysql:
    image: mysql
    container_name: universe-simulator-entity-service-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${US_ES_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${US_ES_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${US_ES_MYSQL_USER}
      - MYSQL_PASSWORD=${US_ES_MYSQL_PASSWORD}
    ports:
      - ${US_ES_MYSQL_PORT}:3306
    volumes:
      - entity-service-mysql:/var/lib/mysql

volumes:
  entity-service-postgres:
  entity-service-mysql:
