version: '3.8'

services:
  postgres:
    image: postgres
    container_name: universe-simulator-entity-service-postgres
    restart: always
    environment:
      - POSTGRES_DB=entity-service
      - POSTGRES_USER=${US_ES_POSTGRES_USER}
      - POSTGRES_PASSWORD=${US_ES_POSTGRES_PASSWORD}
    ports:
      - ${US_ES_POSTGRES_PORT}:5432
    volumes:
      - entity-service-postgres:/var/lib/postgresql/data

  mysql:
    image: mysql
    container_name: universe-simulator-entity-service-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=entity-service
      - MYSQL_ROOT_PASSWORD=${US_ES_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${US_ES_MYSQL_USER}
      - MYSQL_PASSWORD=${US_ES_MYSQL_PASSWORD}
    ports:
      - ${US_ES_MYSQL_PORT}:3306
    volumes:
      - entity-service-mysql:/var/lib/mysql

  vault:
    image: vault
    container_name: universe-simulator-vault
    restart: always
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      - 'VAULT_LOCAL_CONFIG=
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:${US_VAULT_PORT}",
              "tls_disable": true
            }
          },
          "ui": true
        }'
    ports:
      - ${US_VAULT_PORT}:8200
    volumes:
      - vault-logs:/vault/logs
      - vault-file:/vault/file

volumes:
  entity-service-postgres:
  entity-service-mysql:
  vault-logs:
  vault-file:
