CREATE TABLE public.space_entity_kind (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	kind varchar(255) NOT NULL,
	CONSTRAINT space_entity_kind_pkey PRIMARY KEY (id),
	CONSTRAINT uk_7y72hslcv2yyjgkea1gufm3d5 UNIQUE (kind)
);
