CREATE TABLE public.planet (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	age int8 NULL,
	mass float8 NULL,
	orbit_radius float8 NULL,
	orbit_speed float8 NULL,
	radius float8 NULL,
	population int8 NULL,
	kind_id int8 NULL,
	CONSTRAINT planet_pkey PRIMARY KEY (id),
	CONSTRAINT fksqwq0y23wea3s7mob569ion08 FOREIGN KEY (kind_id) REFERENCES space_entity_kind(id)
);
