CREATE TABLE public.moon (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	age int8 NULL,
	mass float8 NULL,
	orbit_radius float8 NULL,
	orbit_speed float8 NULL,
	radius float8 NULL,
	population int8 NULL,
	kind_id int8 NULL,
	CONSTRAINT moon_pkey PRIMARY KEY (id),
	CONSTRAINT fk49kjg3ilxnhnqk0yhcghd9e0b FOREIGN KEY (kind_id) REFERENCES space_entity_kind(id)
);
