CREATE TABLE public.race (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	race varchar(255) NOT NULL,
	CONSTRAINT race_pkey PRIMARY KEY (id),
	CONSTRAINT uk_c332myf9x9ugo6mxkvydkxd26 UNIQUE (race)
);
