CREATE TABLE public.star (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	age int8 NOT NULL,
	mass float8 NOT NULL,
	orbit_radius float8 NOT NULL,
	orbit_speed float8 NOT NULL,
	radius float8 NOT NULL,
	kind_id int8 NOT NULL,
	CONSTRAINT star_pkey PRIMARY KEY (id),
	CONSTRAINT fknw0lkjfi1w6el81uo2eg7ggg1 FOREIGN KEY (kind_id) REFERENCES space_entity_kind(id)
);
