= Project setup

== Java
`Java 11` is the current version of java for the project.

== Gradle
`Gradle Wrapper` is used as a build tool for the project. You don't need to install gradle on
your machine, it will be installed automatically by gradle wrapper. Gradle-related properties
can be found in the `gradle-wrapper.properties` file in the `gradle/wrapper` directory. You can
update the gradle wrapper version with the following command: `./gradlew wrapper
--gradle-version=x.x.x --distribution-type=all`.

== Spring Boot
The project is built with the `Spring Boot v 2.4.x` framework.

== Docker
You need to have `docker` and `docker-compose` installed on your machine. All software
dependencies for the project can be found in the `docker-compose.yml` file.

== Database
`Postgres` is currently used to store the project model entities. `Mysql` can also be used
instead. You can swap datasources for the app by commenting/uncommenting them in the
`application.properties` file. To run a database service locally, use the following command:
`docker-compose -p universe-simulator up -d xxx`, where xxx is the name of a db service
(postgres/mysql). Don't forget to supply env variables to the docker-compose file.

=== Migration
`Liquibase` is used to handle database migratons. Liquibase config is described in the
`db/changelog/db.changelog-master.yaml` file. Add changefiles to the `db/changelog/scripts`
directory. Changefile naming scheme is as follows: `xxx-change-description.extension`.

== Vault
`Hashicorp Vault` is used to store project secrets and other variable configuration. You can set
up vault locally as a docker-compose service by running the following command:
`docker-compose -p universe-simulator up -d vault`. If you stop or restart your container, vault
gets sealed and you'll need to unseal it to be able to use it again.

=== Configuration
When vault is up and running, go to vault ui at `localhost:8200` and follow the setup instructions.
After logging in, enable a new `KV` engine with `universe-simulator` as path. In the new engine
create a secret with `entity-service` as path. Now you can add all your application secrets and
config in the vault's `universe-simulator/entity-service` directory.
