= Project setup

== Java
`Java 11` is the current version of java for the project.

== Gradle
`Gradle Wrapper` is used as a build tool for the project. You don't need to install gradle on
your machine, it will be installed automatically by gradle wrapper. Gradle-related properties
can be found in the `gradle-wrapper.properties` file in the `gradle/wrapper` directory. You can
update the gradle wrapper version with the following command:
`./gradlew wrapper --gradle-version=x.x.x --distribution-type=all`.

== Spring Boot
The project is built with the `Spring Boot v 2.4.x` framework.

=== Profiles
You can have as many spring boot profiles as needed. Profiles usually map to environments (dev,
staging, prod). If you need to override some properties for an environment, add a new
`bootstrap-xxx.properties` or `application-xxx.properties` file where xxx is the name of your
profile. Keep in mind that the `test` profile is used for testing purposes. For local development
you can use the `local` profile. `bootstrap-local.properties` and `application-local.properties`
are excluded from git.

== Docker
You need to have `docker` and `docker-compose` installed on your machine. All software
dependencies for the project can be found in the `docker-compose.yml` file.

== Database
`Postgres` is currently used to store the project model entities. To run a database service locally,
use the following command: `docker-compose -p universe-simulator up -d postgres`. Don't forget to
supply env variables to the docker-compose file.

=== Migration
`Liquibase` is used to handle database migratons. Liquibase config is described in the
`db/changelog/db.changelog-master.yaml` file. Add changefiles to the `db/changelog/scripts`
directory. Changefile naming scheme is as follows: `xxx-change-description.extension`.

== Vault
`Hashicorp Vault` is used to store project secrets and other variable configuration. You can set
up vault locally as a docker-compose service by running the following command:
`docker-compose -p universe-simulator up -d vault`. If you stop or restart your container, vault
gets sealed and you'll need to unseal it to be able to use it again.

=== Configuration
When vault is up and running, go to vault ui at `localhost:8200` and follow the setup instructions.
After logging in, enable a new `KV` engine with `universe-simulator` as path. This root path maps
to the `spring.cloud.vault.kv.backend` property in `bootstrap.properties`. In the new engine create
a secret with `entity-service` as path. This path maps to the `spring.application.name` property
in `bootstrap.properties`. Additionally, you can add as many profile-specific paths as needed.
These paths map to spring boot profiles (e.g. dev, staging, prod). Now you can add secrets and
config in vault's `universe-simulator/entity-service/xxx` directory, where xxx maps to spring boot
profiles.

== CI/CD
`Github Actions` is used for automating the project workflow. The workflow file can be found in the
`.github/workflows` directory. Currently, the file contains only CI part of the workflow, with CD
to be added later. 

== Https/TLS
Application has support for `Https/TLS` and `http/2` protocol is also enabled. You need to have a
keystore file named `universe-simulator.p12` in your `${HOME}/universe-simulator` directory. The
certificate in the keystore can be either self-signed or provided by a CA. You can use java's
`keytool` utility for working with keystore. To create a keystore file with a self-signed certificate
run the following command: `keytool -genkeypair -alias universe-simulator -keyalg RSA
-validity <validity-in-days> -keystore universe-simulator.p12` and follow the instructions. You can
verify the contents of the keystore file with the following command:
`keytool -list -v -keystore universe-simulator.p12`. Keep in mind that TLS is disabled when running
the application with `test` profile.
