on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build --watch-fs --info --stacktrace
      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: bootBuildImage --watch-fs --info --stacktrace
        env:
          US_DOCKER_REGISTRY_USER: ${{ secrets.US_DOCKER_REGISTRY_USER }}
          US_DOCKER_REGISTRY_PASSWORD: ${{ secrets.US_DOCKER_REGISTRY_PASSWORD }}
